site_name: Software de Gestión
site_url: https://geravallejos.github.io/notasVentas/
dev_addr: 'localhost:9000'
nav:
    - Introducción: index.md
    - Guía de Instalación: 
        - Django: instalacion/instalacion_Django.md
        - React: instalacion/instalacion_React.md
    - Dependencias:
        - Django:
            - Django Rest Framework: dependencias/django/django_rest_framework.md
            - Rest Framework SimpleJWT: dependencias/django/rest_framework_simplejwt.md
            - Django Cors Headers: dependencias/django/corsheaders.md
            - Django Axes: dependencias/django/axes.md
            - Boto3: dependencias/django/boto3.md
        - React:
            - React Dom: dependencias/react/reactdom.md
            - React Router: dependencias/react/reactRouter.md
            - Axios: dependencias/react/axios.md
            - Date fns: dependencias/react/date-fns.md
            - Excel JS: dependencias/react/exceljs.md
            - Notistack: dependencias/react/notistack.md
            - React Hook Form: dependencias/react/react-hook-form.md
            - Yup: dependencias/react/yup.md
            - Material UI: dependencias/react/mui.md
            - Redux Tool Kit: dependencias/react/reduxToolKit.md
    - Estructura Backend: 
        - Proyecto: 
            - __pycache__.py: proyecto/backend/nota_ventas/pycache.md
            - __init__.py: proyecto/backend/nota_ventas/init.md
            - asgi.py: proyecto/backend/nota_ventas/asgi.md
            - settings.py: proyecto/backend/nota_ventas/settings.md
            - urls.py: proyecto/backend/nota_ventas/urls.md
            - wsgi.py: proyecto/backend/nota_ventas/wsgi.md
        - Aplicación:
            - migrations: proyecto/backend/nota_app/migrations.md
            - __init__.py: proyecto/backend/nota_app/init_app.md
            - admin.py: proyecto/backend/nota_app/admin.md
            - apps.py: proyecto/backend/nota_app/apps.md
            - auth_urls.py: proyecto/backend/nota_app/auth_urls.md
            - forms.py: proyecto/backend/nota_app/forms.md
            - middleware.py: proyecto/backend/nota_app/middleware.md
            - models.py: proyecto/backend/nota_app/models.md
            - serializer.py : proyecto/backend/nota_app/serializer.md
            - urls.py: proyecto/backend/nota_app/urls_app.md
            - views.py: proyecto/backend/nota_app/views.md
    - Estructura Frontend:
        - App.jsx: proyecto/frontend/src/app.md
        - index.css: proyecto/frontend/src/indexcss.md
        - main.jsx: proyecto/frontend/src/main.md
        - store.js: proyecto/frontend/src/store.md
        - Auth:
            - authSlice.js: proyecto/frontend/src/auth/authSlice.md
            - authThunks.js: proyecto/frontend/src/auth/authThunk.md
        - Assets:
            - images, iconos, mapas: proyecto/frontend/src/assets/assets.md
        - Components:
            - common: 
                - ActionButton.jsx: proyecto/frontend/src/components/common/actionButton.md
                - ComunaAutoComplete.jsx: proyecto/frontend/src/components/common/comunaAutoComplete.md
                - ConfirmDialog.jsx: proyecto/frontend/src/components/common/confirmDialog.md
                - CSRFLoader.jsx: proyecto/frontend/src/components/common/csrfLoader.md
                - CustomToolbar.jsx: proyecto/frontend/src/components/common/customToolbar.md
                - DropZone.jsx: proyecto/frontend/src/components/common/dropZone.md
                - GlobalLoader.jsx: proyecto/frontend/src/components/common/globalLoader.md
                - PickingLoad.jsx: proyecto/frontend/src/components/common/pickingLoad.md
                - SearchSelect.jsx: proyecto/frontend/src/components/common/searchSelect.md
            - dashboard:
                - Dashboard.jsx: proyecto/frontend/src/components/dashboard/dashboard.md
                - FilterComponent.jsx: proyecto/frontend/src/components/dashboard/filterComponent.md
                - MapaDespachos.jsx: proyecto/frontend/src/components/dashboard/mapaDespachos.md
            - dataGrids:
                - NotasDataGrid.jsx: proyecto/frontend/src/components/dataGrids/notasDataGrid.md
                - FacturasDataGrid.jsx: proyecto/frontend/src/components/dataGrids/facturasDataGrid.md
                - SabadoMesGrid.jsx: proyecto/frontend/src/components/dataGrids/sabadoMesGrid.md
                - HistoricoSabados.jsx: proyecto/frontend/src/components/dataGrids/historicoSabados.md
            - forms:
                - LoginForm.jsx: proyecto/frontend/src/components/forms/loginForm.md
                - NotaForm.jsx: proyecto/frontend/src/components/forms/notaForm.md
                - MPrimasForm.jsx: proyecto/frontend/src/components/forms/mPrimasForm.md
                - PickingForm.jsx: proyecto/frontend/src/components/forms/pickingForm.md
            - modal:
                - EditNotaModal.jsx: proyecto/frontend/src/components/modal/editNotaModal.md
                - MateriasPrimasModal.jsx: proyecto/frontend/src/components/modal/materiasPrimasModal.md
                - PDFMetadataModal.jsx: proyecto/frontend/src/components/modal/pdfMetadataModal.md
            - ui:
                - navBar.jsx: proyecto/frontend/src/components/ui/navBar.md
                - sideBar.jsx: proyecto/frontend/src/components/ui/sideBar.md  
        - Hooks:
            - useLoginForm.js: proyecto/frontend/src/hooks/useLoginForm.md
            - useNotaForm.js: proyecto/frontend/src/hooks/useNotaForm.md
            - usePDFMetadata.js: proyecto/frontend/src/hooks/usePDFMetadata.md    
        - Layouts:
            - AppLayout.jsx: proyecto/frontend/src/layouts/appLayout.md
            - AuthLayout.jsx: proyecto/frontend/src/layouts/authLayout.md     
        - Pages:
            - LoginPage.jsx: proyecto/frontend/src/pages/loginPage.md
            - NotasDataPage.jsx: proyecto/frontend/src/pages/notasDataPage.md
            - NotasPage.jsx: proyecto/frontend/src/pages/notasPage.md
        - Routes:
            - Routes.jsx: proyecto/frontend/src/routes/routes.md
            - loader.js: proyecto/frontend/src/routes/loader.md
            - GroupsRouter.jsx: proyecto/frontend/src/routes/groupsRouter.md
        - Theme:
            - AppTheme.jsx: proyecto/frontend/src/theme/appTheme.md
            - theme.js: proyecto/frontend/src/theme/theme.md   
        - Utils: 
            - api.js: proyecto/frontend/src/utils/api.md
            - dataGridEs.js: proyecto/frontend/src/utils/dataGridEs.md
            - exportExcel.js: proyecto/frontend/src/utils/exportExcel.md
            - formatearRut.js: proyecto/frontend/src/utils/formatearRut.md
            - normalizarNombre.js: proyecto/frontend/src/utils/normalizarNombre.md
        - Archivos fuera de src:
            - eslint.config.js: proyecto/frontend/Afuera/eslintConfig.md
            - index.html: proyecto/frontend/Afuera/indexHtml.md
            - vercel.json: proyecto/frontend/Afuera/vercelJson.md
            - vite.config.js: proyecto/frontend/Afuera/viteConfig.md
                 
theme:
  name: material
  palette:
    scheme: default
  features:
    - content.code.annotate

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      linenums: true
      pygments_style: monokai
  - pymdownx.tabbed
  - pymdownx.inlinehilite